- id: living_room_close_all_shutters
  alias: 'Living room: Close all roller shutters on double tap front switch down (S2)'
  description: Double tap down switch of front shutter
  trigger:
  - event_data:
      entity_id: zwave.livingroom_cover_front
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - entity_id: group.tv_room_roller_shutters
    service: cover.close_cover
- id: living_room_open_all_shutters
  alias: 'Living room: Open all roller shutters on double tap front switch up (S1)'
  description: Double tap down switch of front shutter
  trigger:
  - event_data:
      entity_id: zwave.livingroom_cover_front
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - entity_id: group.tv_room_roller_shutters
    service: cover.open_cover
