- id: 'door_opens_shutter'
  alias: door opens shutter
  trigger:
  - platform: state
    entity_id: binary_sensor.neq0945549_state
    to: 'on'
  action:
    service: cover.open_cover
    entity_id: cover.kitchen_cover_level
- id: 'open_shutters_in_the_morning'
  alias: open shutters in the morning
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:30:00
  action:
  - service: cover.open_cover
    entity_id: group.all_covers
- id: close_shutters_in_the_evening
  alias: close shutters in the evening
  trigger:
  - platform: sun
    event: sunset
    offset: 01:00:00
  action:
  - service: cover.close_cover
    entity_id: group.all_covers
- id: 'close_all_shutters_on_double_tap'
  alias: close all shutters on double tap
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_cover
      scene_id: 24
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_front
      scene_id: 24
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_side
      scene_id: 24
  action:
  - service: cover.close_cover
    entity_id: group.all_covers
- id: 'open_all_shutters_on_double_tap'
  alias: open all shutters on double tap
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_cover
      scene_id: 14
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_front
      scene_id: 14
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_side
      scene_id: 14
  action:
  - service: cover.open_cover
    entity_id: group.all_covers
- id: 'shadow_mode_for_all_shutters_on_tripple_tap'
  alias: shadow mode for all shutters on tripple tap
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_cover
      scene_id: 25
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_front
      scene_id: 25
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.salon_cover_side
      scene_id: 25
  action:
  - service: cover.set_cover_position
    data:
      entity_id: group.all_covers
      position: 30
- id: 'wake_up_light_in_bedroom'
  alias: wake up light in bedroom
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state
      }}'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.wakeup_weekends
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_on
    data:
      entity_id: light.deckenlampe_schlafzimmer
      profile: relax
    data_template:
      transition: '{{ states.input_number.wakeup_duration.state | multiply(60) | float
        }}'
