- alias: 'door opens shutter'
  trigger:
    - platform: state
      entity_id: binary_sensor.neq0945549_state
      to: 'on'
  action:
    service: cover.open_cover
    entity_id: cover.kitchen_cover_level

- alias: 'open shutters in the morning'
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:30:00'
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_cover_level
    - service: cover.open_cover
      entity_id: cover.salon_cover_front_level
    - service: cover.open_cover
      entity_id: cover.salon_cover_side_level

- alias: 'close shutters in the evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '01:00:00'
  condition:
    - sevice: time
      after: '22:00:00'
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_cover_level
    - service: cover.close_cover
      entity_id: cover.salon_cover_front_level
    - service: cover.close_cover
      entity_id: cover.salon_cover_side_level

- alias: 'close all shutters on double tap'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_cover
        scene_id: 24
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.salon_cover_front
        scene_id: 24
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.salon_cover_side
        scene_id: 24
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_cover_level
    - service: cover.close_cover
      entity_id: cover.salon_cover_front_level
    - service: cover.close_cover
      entity_id: cover.salon_cover_side_level

- alias: 'open all shutters on double tap'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_cover
        scene_id: 14
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.salon_cover_front
        scene_id: 14
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.salon_cover_side
        scene_id: 14
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_cover_level
    - service: cover.open_cover
      entity_id: cover.salon_cover_front_level
    - service: cover.open_cover
      entity_id: cover.salon_cover_side_level
