homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # http://www.mapcoordinates.net/
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# hass.io / not sure if needed when discovery: is active
hassio:

ios:
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

zone:
  name: Work Bernd
  latitude: !secret bernd_work_latitude
  longitude: !secret bernd_work_longitude
  radius: 500
  icon: mdi:domain

sensor: !include sensors.yaml

# Homematic CCU
homematic:
  hosts:
    wired:
      ip: !secret homematic_ip

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

light:
  platform: hue
  host: !secret hue_ip

media_player:
  platform: sonos

device_tracker:
  - platform: unifi
    username: !secret unifi_username
    password: !secret unifi_password
  - platform: owntracks
    waypoints: True
    waypoint_whitelist:
      - iphone_bernd

# input components
input_number:
  wakeup_hour:
    name: Hour
    icon: mdi:clock-in
    initial: 6
    min: 0
    max: 23
    step: 1

  wakeup_minutes:
    name: Minutes
    icon: mdi:clock-in
    initial: 30
    min: 0
    max: 55
    step: 5

  wakeup_duration:
    name: Light fade-in duration
    icon: mdi:clock-in
    initial: 10
    min: 5
    max: 60
    step: 5

input_boolean:
  wakeup:
    name: 'Enable wakeup light'
    icon: mdi:power
    initial: off

  wakeup_weekends:
    name: 'Wakeup weekends'
    icon: mdi:power
    initial: off

#mqtt:
#  broker: m21.cloudmqtt.com
#  port: 26282
#  username: !secret mqtt_username
#  password: !secret mqtt_password

notify:
  - name: web
    platform: html5
    gcm_api_key: !secret gcm_sender_key
    gcm_sender_id: !secret gcm_sender_id

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
