homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # http://www.mapcoordinates.net/
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# data logging
recorder:
    purge_keep_days: 30
    db_url: !secret mariadb_url

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# hass.io / not sure if needed when discovery: is active
hassio:

ios:
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

zone:
  name: Work Bernd
  latitude: !secret bernd_work_latitude
  longitude: !secret bernd_work_longitude
  radius: 500
  icon: mdi:domain

# Homematic CCU
homematic:
  interfaces:
    rf_ccu2_rpc:
      host: !secret homematic_host
      port: 2001
      resolvenames: json
      username: !secret homematic_username
      password: !secret homematic_password
    groups:
        host: !secret homematic_host
        port: 9292
        resolvenames: json
        username: !secret homematic_username
        password: !secret homematic_password
        path: /groups
  hosts:
    ccu2:
      host: !secret homematic_host
      username: !secret homematic_username
      password: !secret homematic_password

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

hue:
  bridges:
    - host: !secret hue_ip

media_player:
  platform: sonos

device_tracker:
  - platform: unifi
    host: bibliothekar
    port: 8443
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
  # - platform: owntracks
  #   waypoints: True
  #   waypoint_whitelist:
  #     - iphone_bernd

## input components ##
input_number:
  wakeup_hour:
    name: Hour
    icon: mdi:clock-in
    initial: 8
    min: 0
    max: 23
    step: 1

  wakeup_minutes:
    name: Minutes
    icon: mdi:clock-in
    initial: 0
    min: 0
    max: 55
    step: 5

  wakeup_duration:
    name: Light fade-in duration
    icon: mdi:clock-in
    initial: 10
    min: 5
    max: 60
    step: 5

input_boolean:
  wakeup:
    name: 'Enable wakeup light'
    icon: mdi:power
    initial: off

  wakeup_weekends:
    name: 'Wakeup weekends'
    icon: mdi:power
    initial: off

#mqtt:
#  broker: m21.cloudmqtt.com
#  port: 26282
#  username: !secret mqtt_username
#  password: !secret mqtt_password

notify:
  - name: web
    platform: html5
    gcm_api_key: !secret gcm_sender_key
    gcm_sender_id: !secret gcm_sender_id

alexa:
  intents:
    LocateIntent:
      action:
        service: notify.pushover
        data:
          message: Your location has been queried via Alexa.
      speech:
        type: plaintext
        text: >
          {%- for state in states.device_tracker -%}
            {%- if state.name.lower() == User.lower() -%}
              {{ state.name }} ist {{ state.state }}
            {%- endif -%}
          {%- else -%}
            Tut mir leid. Ich weiß nicht wo {{User}} ist.
          {%- endfor -%}
    WhereAreWeIntent:
      speech:
        type: plaintext
        text: >
          {%- if is_state('device_tracker.espirit_bernd', 'home') -%}
            Bernds iPhone ist zuhause.
          {%- else -%}
            Bernds iPhone ist nicht zuhause.
          {% endif %}

sensor: !include sensors.yaml
group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
